<datalist id="listHoteles">
	<option value="Hard Rock Hotel &amp; Casino">Hard Rock Hotel &amp; Casino</option>
	<option value="Hotel Excellence">Hotel Excellence</option>
	<option value="AlSol Del Mar – Luxury Condo">AlSol Del Mar – Luxury Condo</option>
	<option value="AlSol Tiara Cap Cana Boutique Resort">AlSol Tiara Cap Cana Boutique Resort</option>
	<option value="AlSol Luxury Village">AlSol Luxury Village</option>
	<option value="Bávaro Princess All Suites Resort Spa &amp; Casino">Bávaro Princess All Suites Resort Spa &amp; Casino</option>
	<option value="Barceló Bavaro Beach">Barceló Bavaro Beach</option>
	<option value="Barceló Palace Deluxe">Barceló Palace Deluxe</option>
	<option value="Be Live Collection Punta Cana">Be Live Collection Punta Cana</option>
	<option value="Catalonia Royal Bávaro">Catalonia Royal Bávaro</option>
	<option value="Catalonia Punta Cana">Catalonia Punta Cana</option>
	<option value="Club Hotel Riu Bambu">Club Hotel Riu Bambu</option>
	<option value="Dreams Palm Beach">Dreams Palm Beach</option>
	<option value="Eden Roc at Cap Cana">Eden Roc at Cap Cana</option>
	<option value="Four Points by Sheraton Punta Cana Village">Four Points by Sheraton Punta Cana Village</option>
	<option value="Gran Bahía Príncipe Esmeralda">Gran Bahía Príncipe Esmeralda</option>
	<option value="Gran Bahía Príncipe Punta Cana">Gran Bahía Príncipe Punta Cana</option>
	<option value="Gran Bahía Príncipe Turquesa">Gran Bahía Príncipe Turquesa</option>
	<option value="Gran Palladium Punta Cana Resort &amp; Spa Hotel">Gran Palladium Punta Cana Resort &amp; Spa Hotel</option>
	<option value="Gran Palladium Bávaro Resort &amp; Spa Hotel">Gran Palladium Bávaro Resort &amp; Spa Hotel</option>
	<option value="Hotel Vista Sol Punta Cana">Hotel Vista Sol Punta Cana</option>
	<option value="IFA Villa Bávaro Resort &amp; Spa">IFA Villa Bávaro Resort &amp; Spa</option>
	<option value="Iberostar Grand Hotel Bavaro">Iberostar Grand Hotel Bavaro</option>
	<option value="Luxury Bahía Príncipe Esmeralda">Luxury Bahía Príncipe Esmeralda</option>
	<option value="Majestic Colonial">Majestic Colonial</option>
	<option value="Majestic Elegance">Majestic Elegance</option>
	<option value="Majestic Mirage">Majestic Mirage</option>
	<option value="Memories Splash">Memories Splash</option>
	<option value="Melia Caribe Tropical">Melia Caribe Tropical</option>
	<option value="Now Larimar">Now Larimar</option>
	<option value="Natura Park Beach Eco Resort &amp; Spa">Natura Park Beach Eco Resort &amp; Spa</option>
	<option value="Ocean Blue &amp; Sand Beach Resort">Ocean Blue &amp; Sand Beach Resort</option>
	<option value="Paradisus Punta Cana Resort">Paradisus Punta Cana Resort</option>
	<option value="Paradisus Palma Real – The Reserve">Paradisus Palma Real – The Reserve</option>
	<option value="Paradisus Palma Real">Paradisus Palma Real</option>
	<option value="Punta Palmera Cap Cana">Punta Palmera Cap Cana</option>
	<option value="Riu Palace Punta Cana">Riu Palace Punta Cana</option>
	<option value="Riu Palace Bávaro">Riu Palace Bávaro</option>
	<option value="Riu Palace Macao">Riu Palace Macao</option>
	<option value="Riu Naiboa">Riu Naiboa</option>
	<option value="Royalton Punta Cana Resort &amp; Casino">Royalton Punta Cana Resort &amp; Casino</option>
	<option value="Sanctuary Cap Cana">Sanctuary Cap Cana</option>
	<option value="Tropical Princess Beach Resort &amp; Spa">Tropical Princess Beach Resort &amp; Spa</option>
	<option value="Tortuga Bay Hotel">Tortuga Bay Hotel</option>
	<option value="The Westin Punta Cana Resort &amp; Club">The Westin Punta Cana Resort &amp; Club</option>
	<option value="The Royal Suites Turquesa">The Royal Suites Turquesa</option>
	<option value="The Palms Punta Cana">The Palms Punta Cana</option>
	<option value="Xeliter Caleton Villas">Xeliter Caleton Villas</option>
	<option value="Xeliter Golden Bear Lodge Cap Cana">Xeliter Golden Bear Lodge Cap Cana</option>
	<option value="Occidental Caribe">Occidental Caribe</option>
	<option value="Occidental Punta Cana">Occidental Punta Cana</option>
	<option value="Secret Cap Cana">Secret Cap Cana</option>
	<option value="Secret Royal Beach">Secret Royal Beach</option>
	<option value="Now Onix ">Now Onix </option>
	<option value="Riu República">Riu República</option>
	<option value="Bahia Principe Ambar">Bahia Principe Ambar</option>
	<option value="Bahia Principe Fantasy">Bahia Principe Fantasy</option>
</datalist>